subscription        = ""
sec_tenant          = ""
client              = ""
client_secret       = ""
resource_group_name = ""
secret_name         = ""
secret_value        = ""
//spdlsec             = "
